import './globals.css'
import Footer from './components/footer'
import Header from './components/header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (


    <html >
      <body>
        <Header />
        {children}
        <Footer />
      </body>

    </html>


  )
}

