#services:
#  mongo:
#    image: "mongo:latest"
#    container_name: mongo-container
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=faisal
#      - MONGO_INITDB_ROOT_PASSWORD=123
#  mongo-express:
#    image: "mongo-express:latest"
#    container_name: mongo-express-container
#    restart: always
#    ports:
#      - "8082:8081"
#    depends_on:
#      - mongo
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_MONGODB_ADMINUSERNAME: faisal
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
#
#volumes:
#  mongo_data: {}
#
#networks:
#  default:
#    name: mongo_network

version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=faisal
      - MONGO_INITDB_ROOT_PASSWORD=123
volumes:
  data: {}

networks:
  default:
    name: atypon