name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_PREFIX: faisal2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth service
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/auth:${{ github.sha }} ./auth
          docker push ${{ env.IMAGE_PREFIX }}/auth:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/auth:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/auth:latest
          docker push ${{ env.IMAGE_PREFIX }}/auth:latest

      - name: Build and push projects service
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/projects:${{ github.sha }} ./projects
          docker push ${{ env.IMAGE_PREFIX }}/projects:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/projects:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/projects:latest
          docker push ${{ env.IMAGE_PREFIX }}/projects:latest

      - name: Build and push code-executor service
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/codeservice:${{ github.sha }} ./codeService
          docker push ${{ env.IMAGE_PREFIX }}/codeservice:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/codeservice:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/codeservice:latest
          docker push ${{ env.IMAGE_PREFIX }}/codeservice:latest

      - name: Build and push frontend
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/frontend:${{ github.sha }} ./client
          docker push ${{ env.IMAGE_PREFIX }}/frontend:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/frontend:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/frontend:latest
          docker push ${{ env.IMAGE_PREFIX }}/frontend:latest
